#vich_uploader:
db_driver: orm
mappings:
    acmarche_lunch_commerce_image:
        namer:              vich_uploader.namer_uniqid
        uri_prefix:         /data/commerces
        upload_destination: "%kernel.root_dir%/../web/data/commerces"
        inject_on_load:     false
        delete_on_update:   true
        delete_on_remove:   true
    acmarche_lunch_produit_image:
        namer:              vich_uploader.namer_uniqid
        uri_prefix:         /data/produits
        upload_destination: "%kernel.root_dir%/../web/data/produits"
        inject_on_load:     false
        delete_on_update:   true
        delete_on_remove:   true
    acmarche_lunch_categorie_image:
        namer:              vich_uploader.namer_uniqid
        uri_prefix:         /data/produits
        upload_destination: "%kernel.root_dir%/../web/data/produits"
        inject_on_load:     false
        delete_on_update:   true
        delete_on_remove:   true
