<?php

namespace AcMarche\LunchBundle\Repository;

use AcMarche\LunchBundle\Entity\Categorie;
use AcMarche\LunchBundle\Entity\Commerce;
use AcMarche\SecurityBundle\Entity\User;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{

    public function search($args)
    {
        $qb = $this->createQueryBuilder('categorie');
        $qb->leftJoin('categorie.produits', 'produits', 'WITH');
        $qb->addSelect('produits');

        $motclef = isset($args['motclef']) ? $args['motclef'] : null;
        $commerce = isset($args['commerce']) ? $args['commerce'] : null;

        if ($motclef) {
            $qb->andWhere('categorie.nom LIKE :clef')
                ->setParameter('clef', '%'.$motclef.'%');
        }

        $qb->addOrderBy('categorie.nom');

        $query = $qb->getQuery();

        $results = $query->getResult();

        return $results;
    }

    /**
     * @param User $user
     * @return Categorie[]
     */
    public function getOwnedByUser(User $user)
    {
        $em = $this->getEntityManager();
        $commerces = $em->getRepository(Commerce::class)->getCommercesOwnedByUser(
            $user
        );

        if (!$commerces) {
            return [];
        }

        return $this->search(['commerce' => $commerces]);
    }

}
