<?php

namespace AcMarche\LunchBundle\Repository;

/**
 * CommandePaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandePaiementRepository extends \Doctrine\ORM\EntityRepository
{
}
