<?php

namespace AcMarche\LunchBundle\Repository;

/**
 * LieuxLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuxLivraisonRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Pour remplir select du form
     * @return array
     */
    public function getForSearch()
    {
        $qb = $this->createQueryBuilder('lieux_livraison');

        $qb->orderBy('lieux_livraison.nom');
        $query = $qb->getQuery();

        $results = $query->getResult();
        $lieux = array();

        foreach ($results as $lieu) {
            $lieux[$lieu->getNom()] = $lieu->getId();
        }

        return $lieux;
    }
}
