<?php

namespace AcMarche\LunchBundle\Repository;

/**
 * Parametrepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Parametrepository extends \Doctrine\ORM\EntityRepository
{
}
