<?php

namespace AcMarche\LunchBundle\Repository;

/**
 * StripeChargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StripeChargeRepository extends \Doctrine\ORM\EntityRepository
{
}
