<?php

namespace AcMarche\LunchBundle\DataFixtures\ORM;

Class FixtureLunchConstant
{
    const CATEGORIES = [
        'Assiettes froides',
        'Boissons et vins',
        'Lunchs classiques',
        'Sandichs spécialisés',
        'Lunchs chauds',
        'Plats préparés',
    ];

    const COMMERCES = ["porte", "delice", "babe", "dagobert", "midi","vin"];

    const PRODUIS_LUNCH_CLASSIQUES = [
        ["babe" => 'Américain (pur boeuf)'],
        ["babe" => 'Boulette'],
        ["porte" => 'Chèvre'],
        ["porte" => 'Crabe'],
        ["babe" => 'Gouda'],
        ["porte" => 'Poulet andalouse'],
        ["delice" => 'Poulet curry'],
        ["delice" => 'Philadelphia fines herbes'],
        ["dagobert" => 'Roti moutarde'],
        ["dagobert" => 'Crevettes'],
        ["dagobert" => 'Saumon fumé'],
        ["midi" => 'Poulet mayonnaise'],
        ["midi" => 'Thon piquant'],
        ["midi" => 'Thon mayonnaise'],
    ];

    const PRODUIS_LUNCH_SPECIALISE = [
        ["porte" => 'Anglais'],
        ["babe" => 'Ardennais'],
        ["delice" => 'Berger'],
        ["midi" => 'Campagnard'],
        ["dagobert" => 'Martino'],
        ["midi" => 'Norvégien'],
        ["delice" => 'Niçois'],
        ["midi" => 'Paysan'],
        ["porte" => 'Tartare italien'],
        ["babe" => 'Toscane'],
        ["dagobert" => 'Pise'],
        ["babe" => 'Club'],
    ];

    const INGREDIENTS = [
        'pain de viande',
        'andalouse',
        'oignons',
        'salade',
        'oeuf',
        'jambon fumé',
        'mayonnaise',
        'chèvre',
        'lard grillé',
        'miel',
        'roasbeef',
        'tomates',
        'cressonnette',
        'sauce yaourt pesto rouge',
        'jambon',
        'fromage',
        'concombre',
        'maïs',
        'cornichons',
        'moutarde',
        'anchois',
        'olives',
        'mozzarella',
        'herbes de Provence',
        'vinaigre balsamique',
        'roquette',
        'parmesan',
        'poulet',
        'huile d\'olive',
        'crabe',
        'émincés poulet tex-mex',
        'cerneaux de noix',
    ];

    const SUPLLEMENTS = [
        'Ananas',
        'Anchois',
        'Bacon',
        'Boulette entière',
        'Brie',
        'Carotte',
        'Chèvre',
        'Concombre',
        'Cornichons',
        'Cressonnette',
        'Gouda',
        'Jambon cui',
        'Jambon italien',
        'Maïs ',
        'Noix',
        'euf(1/2)',
        'Oignons frais',
        'Oignons frits ',
        'Oignons vinaigre',
        'Olive ',
        'Parmesan',
        'Pesto rouge',
        'Pesto vert',
        'Philadelphia fines herbes',
        'Philadelphia nature',
        'Pignons',
        'Pêche ',
        'Roquette',
        'Roti de dinde',
        'Salade classique',
        'Salami',
        'Sauce andalouse',
        'Sauce bicky',
        'Sauce cocktail',
        'Sauce ketchup',
        'Sauce martino(piquant)',
        'Sauce mayonnaise',
        'Sauce moutarde',
        'Saumon fumé',
        'Tomates fraiches',
        'Tomates séchées ',
    ];

}